version: '3.8'

services:
  backend:
    build: ./backend
    container_name: farm-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - farm-network

  frontend:
    build: .
    container_name: farm-frontend
    ports:
      - "4173:80"
    depends_on:
      - backend
    networks:
      - farm-network

networks:
  farm-network:
    driver: bridge
