version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: farm-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - farm-network
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: farm-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./public:/app/public  # 👈 monta la carpeta public aquí
    env_file:
      - ./backend/.env
    networks:
      - farm-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  farm-network:
    driver: bridge
